# Generated by Django 5.1.4 on 2025-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_remove_books_author_remove_books_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gif',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
