# Generated by Django 5.1.4 on 2024-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
