# Generated by Django 5.1.4 on 2024-12-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person')),
            ],
        ),
    ]
